/**
 * Standard Application Error Codes
 * Enterprise Single Source of Truth for Error Codes
 */
export const ErrorCodes = {
    // 400 Bad Request
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    BAD_REQUEST: 'BAD_REQUEST',
    MISSING_FIELDS: 'MISSING_FIELDS',
    INVALID_FORMAT: 'INVALID_FORMAT',

    // 401 Unauthorized
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_TOKEN: 'INVALID_TOKEN',
    EXPIRED_TOKEN: 'EXPIRED_TOKEN',

    // 403 Forbidden
    FORBIDDEN: 'FORBIDDEN',
    ACCESS_DENIED: 'ACCESS_DENIED',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    CORS_ERROR: 'CORS_ERROR',

    // 404 Not Found
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',

    // 409 Conflict
    CONFLICT: 'CONFLICT',
    DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',

    // 422 Unprocessable Entity
    UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',

    // 500 Internal Server Error
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    DATABASE_ERROR: 'DATABASE_ERROR',
    EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',

    // Special
    SHADOW_BANNED: 'SHADOW_BANNED'
};
